### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by hfiguiere** [guardian/typerighter#129]
There is no explicit or easily locatable license for this project. 

Please add license information to this project.

Thank you !

**Comment by losowsky** [comment]
+1. The article about this said it's open source, but not seeing a license to confirm that! (Src: https://www.theguardian.com/info/2021/jan/26/how-we-made-typerighter-the-guardians-style-guide-checker )

**Comment by petricek** [comment]
+1, please add a license 
(https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository)

**Comment by petricek** [comment]
The prosemirror-typerighter is licensed as Apache License 2.0, is this released under the same license?
https://github.com/guardian/prosemirror-typerighter/blob/main/LICENSE.md

**Comment by jonathonherbert** [comment]
What an oversight! Thanks for mentioning.
